title: Hi, I'm Pankaj
description: I write my thoughts and experiences here.
show_downloads: false
google_analytics:
theme: jekyll-theme-dinky

github:
  is_project_page: false
  is_user_page: true
  owner_url: https://github.com/y-pankaj
